### PR TITLE
July 2016 NodeSchool Belfast

### PR DESCRIPTION
**Pull request by gangleri**
Putting this PR out there so that we can discuss a July event. Do you think there will be interest?

Changes:
- Update date
- Added some data attributes that I'm using for a twitter bot

### CODE REVIEW

**Comment by bmullan91** [comment]
@gangleri I won't be able to make it to this one - I'll be in NYC ✈️.

One suggestion, perhaps we should start a bit later 18:30 / 19:00. Usually a few people it arrive at this time, and I'm wondering if others are ruling it out because of the start time?

**Comment by gangleri** [comment]
@bmullan91 I'm good to change the time, 19:00 works for me

Anyone else have an opinion?

**Comment by gangleri** [comment]
There doesn't seem to be much interest for a July NodeSchool. I vote we close this PR and forget about a July NodeSchool. We can start again at the end of August.

**Comment by gangleri** [comment]
Closing this due to lack of interest, lets try again in August

**Pull request closed without merging**
